name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building deb package
        run: |
          sudo apt update
          sudo apt install devscripts equivs fuse libfuse2 -y
          sudo mk-build-deps --install
          sudo debuild -us -uc -b
          sudo mkdir -p /output/
          sudo mv ../*.deb /output/
          sudo mv ./*.deb /output/
          sudo QT_PATH="/usr/lib/x86_64-linux-gnu/qt5" bash appimage/create_appimage.sh
          sudo mv build/*.AppImage /output/
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "current"
          prerelease: false
          title: "Latest release"
          files: |
            /output/*

